wandb_version: 1

TU:
  desc: null
  value: 3
TC:
  desc: null
  value: 5
TR:
  desc: null
  value: 50
map_reset_interval:
  desc: null
  value: 50
replay_ratio:
  desc: null
  value: 10
episodes:
  desc: null
  value: 800
alpha:
  desc: null
  value: 0.9
env_count:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1731914115
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.4
      5: 0.17.8
      8:
      - 1
      - 5
      13: linux-x86_64
